---
jupyterhub_bind_url: "http://:8000/jupyter"
jupyterhub_base_url: /jupyter
jupyterhub_install_r_kernel: true
jupyterhub_r_conda_env: rstudio-server

miniforge_install_dir: /opt/rstudio-server_miniforge

jupyterhub_conda_packages:
  - jupyterhub=5.4.4
  - jupyterlab
  - jupyterhub-idle-culler
  - irkernel
